### ISSUE TITLE
Chapter 1: Wrong URL pointer?

### ISSUE THREAD

**Issue by sabrinacales** [astroML/astroML#53]
I’m running throughout the coding examples for the Statistics Data Mining and Machine Learning in Astronomy text. I’ve found that this bit of code gives an error. 

    from astroML.datasets import tools
    target = tools.TARGET_GALAXY
    # main galaxy sample
    plt, mjd, fib = tools.query_plate_mjd_fiber(5, primtarget=target)

I think that the issue might be that the URL is pointing to the wrong place now that DR12 is the public. 

Any suggestions for a solution?

**Comment by jakevdp** [comment]
Thanks for the bug report. It looks like changing the URL from ``.asp`` to ``.aspx`` makes the code work; I pushed a fix in https://github.com/astroML/astroML/commit/a5076d6d9eb74feab0cf2db06bc961a61c7cdc69

If you reinstall ``astroML`` from the latest master branch, the script should work.

Thanks for reporting the bug!

**Comment by jpdeleon** [comment]
I have the latest version of astroML and the aspx  correction is in place. However, I still have this HTTP error which stems from tools.query_plate_mjd_fiber line:
>output = sql_query(query_text).readlines()

Any suggestions?
